select p.PRODUCT_ID,p.PRODUCT_TYPE_ID,oh.PRODUCT_STORE_ID,
oi.QUANTITY as TOTAL_QUANTITY,p.INTERNAL_NAME,f.FACILITY_ID,oi.EXTERNAL_ID,
f.FACILITY_TYPE_ID,ohis.ORDER_HISTORY_ID,oh.ORDER_ID,oi.ORDER_ITEM_SEQ_ID,
ohis.SHIP_GROUP_SEQ_ID from
order_header oh join order_item oi on oh.ORDER_ID=oi.ORDER_ID and oh.STATUS_ID="ORDER_COMPLETED"
join  order_history ohis on ohis.ORDER_ITEM_SEQ_ID=oi.ORDER_ITEM_SEQ_ID and ohis.CREATED_DATE BETWEEN '2023-08-1 00:00:00' AND '2023-09-01 00:00:01'
join product p on p.PRODUCT_ID=oi.PRODUCT_ID join facility f on f.FACILITY_ID=oh.ORIGIN_FACILITY_ID;
