SELECT 
p.PRODUCT_ID
,pf.FACILITY_ID
, ii.AVAILABLE_TO_PROMISE_TOTAL
, ii.QUANTITY_ON_HAND_TOTAL
, (ii.QUANTITY_ON_HAND_TOTAL - ii.AVAILABLE_TO_PROMISE_TOTAL) as DIFFERENCE
from inventory_item ii join product p on p.PRODUCT_ID=ii.PRODUCT_ID join product_facility pf on pf.PRODUCT_ID=p.PRODUCT_ID
where pf.MINIMUM_STOCK>ii.QUANTITY_ON_HAND_TOTAL and QUANTITY_ON_HAND_TOTAL!=0;